{% set name = "winpty-rs" %}
{% set version = "1.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/andfoy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d67f96abc22d4b13efb9a88969caf9929a2e8b1b928843b5ab122455e9640e7f


build:
  skip: true  # [not win]
  number: 0
  build:
  # Build
  - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # License generation
  - cargo-bundle-licenses --format yaml --output "{{ SRC_DIR }}\THIRDPARTY.yml"

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.1,<2.0
    - winpty 0.4.3
  run:
    - python

test:
  imports:
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"